export class STANDING{
  away:{
    draws:number;
    goals:number;
    goalsAgainst:number;
    losses:number;
    wins:number;
  };
  crestURI:string;
  draws:number;
  goalDifference:number;
  goals:number;
  goalsAgainst:number;
  home:{
    draws:number;
    goals:number;
    goalsAgainst:number;
    losses:number;
    wins:number;
  }
  losses:number;
  playedGames:number;
  points:number;
  position:number;
  teamName:string;
  wins:number;
}
